### PR TITLE
Added LikeFeedbackBox to extension

### PR DESCRIPTION
**Pull request by oskaitu**
Added the LikeFeedbackBox to the extension. Uses articleInfo and setArticleInfo from modal.js

### CODE REVIEW

**Review by tfnribeiro — CHANGES_REQUESTED** [review]
Here is how it looks on chrome:
image

I would add some CSS to give some left and right margin, this might be set at the Web but we don't have it in the extension. Here I set 2em margin left and right:

image

Other than that, I think it looks good - I will update the README with instructions to how you can test it yourselves in your browser.

**Comment by mircealungu** [comment]
We could also have both the questions in the same box? With the "help us make zeeguu smarter..." text a bit more generalized.

**Comment by oskaitu** [comment]
Thank you for updating the readme.md, it did help to know where to find the extension after it was built.

I was able to run it locally with the changes that I have made to zeeguu-web.

Regarding the texts, we have some suggestions, that we can talk about to our meeting on Monday :)

I have aligned the text to center and have margin on left and right with 2em. The changes will be seen on this repo after https://github.com/zeeguu/web/pull/318 has been merged.

image

**Comment by oskaitu** [comment]
Added source prop to LikeFeedbackBox

Combined the LikeFeedbackBox and DifficultyFeedbackBox inside a new component "StyledDiv" with the new text

boxescombined

**Review by tfnribeiro — CHANGES_REQUESTED** [review]
Should be good, we need to update to the latest branch of the `zeeguu-web` before merging and building the extension.

**Comment by mircealungu** [comment]
nice! I'll deploy it this afternoon!

**Review by mircealungu — APPROVED** [review]
ok. let's merge and deploy this!

**Comment by mircealungu** [comment]
Dear folks, 

I was about to publish the extension (with a very minor stylistic intervention that you can see in the image) when I discovered something strange. 

The "thank you message" replaces only the difficulty question and leaves the first question and answer visible in an awkward way. Either leave both with the thank you, or replace both. 

image

Can you quickly fix this and then I'll publish?

**Comment by mircealungu** [comment]
tagging you @oskaitu: see message above.

**Comment by mircealungu** [comment]
Also, same problem is also in the web: let's try to fix it there too!

**Comment by oskaitu** [comment]
Hi @mircealungu,

We have now changed the UI so the 'thank you' text appears after clicking either the like or difficulty feedback buttons. Both the like and the difficulty feedback buttons stay on the screen when they have been pressed. Let us know what you think. (We forgot to pull your changes, so the text is still bold. We will do it in a bit)

We had to make some changes to the api, because the fetch for the articleInfo did not get the correct information about whether the user had previously given feedback for the difficulty of an article.

We will commit and push our changes now so you can see them.

https://github.com/zeeguu/browser-extension/assets/100945285/d476c766-e152-4e44-bc83-1f72ca03b8cf

**Comment by Mlth** [comment]
Btw, we also removed the hover-effect from the difficulty-buttons, so that they matched the like-buttons. However, we will try to add hover-effects to both now! 😊

**Comment by mircealungu** [comment]
Nice! thanks for the prompt reply! 

One more, most minor of the observations: the elephant is missing from the "practice your words" box. Is that on purpose?

**Comment by Mlth** [comment]
Hmm, we have gone back in the commit history, and it looks like the elephant has not been in the extension for some time. We have added it now, and made pull requests from our forks 👍

Here are the new pull requests we have made:
API: https://github.com/zeeguu/api/pull/129
Web: https://github.com/zeeguu/web/pull/324
Extension: https://github.com/zeeguu/browser-extension/pull/51

**Comment by mircealungu** [comment]
Tussind Tak! 
I've asked for a few refactorings for the web RQ. But not it's friday and ti's late. 
Given that the functionality is there already, do you want me to merge and you send a new PR with the refactoring next week?

**Comment by oskaitu** [comment]
Yeah, that would work for us. If you think it looks good and works as intended you can merge it in. We will then take a look at the refactoring requests in web and make a new PR :)

**Pull request merged**
